### ISSUE TITLE
PROJECT CHECKLIST

### ISSUE THREAD

**Issue by psharratt** [rfdornelles/mds_ML_project#7]
- [ ] Frame the problem
- [ ] Get data
- [ ] Data preparation
- [ ] Explore models
- [ ] Fine-tune models
- [ ] Presentation 
- [ ] Launch and maintain
